server/LAS_LOG/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('server.service.LAS_LOGs.urls', 'LAS_LOGs'), namespace='LAS_LOGs')),
    path('users/', include(('server.service.users.urls', 'users'), namespace='users')),
    path('topics/', include('server.service.LAS_LOGs.urls')),
    path('tags/', include('server.service.tags.urls'))
]

server/service/LAS_LOGs/urls.py
"""定义LAS_LOGs的URL模式"""

from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('topics', views.topics, name='topics'),
    path('topics/(<topic_id>)', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/(<topic_id>)/', views.new_entry, name='new_entry'),
    path('edit_entry/(<entry_id>)/', views.edit_entry, name='edit_entry'),
    path('links/', views.links, name='links'),
    path('new_link/', views.new_link, name='new_link'),
]

server/service/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('register/', views.register, name='register'),
]

server/service/LAS_LOGs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, models.CASCADE)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """留言"""

    topic = models.ForeignKey(Topic, models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, models.CASCADE)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text[:50] + "..."


class Link(models.Model):
    """链接页面"""

    text = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Work(models.Model):
    """链接页面"""

    title = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, models.CASCADE)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.title

server/service/LAS_LOGs/forms.py
from django import forms
from .models import Topic, Entry, Link


class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class LinkForm(forms.ModelForm):

    class Meta:
        model = Link
        fields = ['text']
        labels = {'text': ''}

server/service/LAS_LOGs/views.py
from django.shortcuts import render
from .models import Topic, Entry, Link
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import TopicForm, EntryForm, LinkForm
from django.contrib.auth.decorators import login_required


def index(request):
    """LAS记事本的主页 LAS_LOG mian page"""
    return render(request, 'LAS_LOG/index.html')


@login_required
def topics(request):
    """显示所有主题 show all topics"""
    all_topic = Topic.objects.order_by('date_added')
    context = {'topics': all_topic}
    return render(request, 'LAS_LOG/topics.html', context)


@login_required
def topic(request, topic_id):
    """显示单个主题及其所有的条目"""
    topic_specific = Topic.objects.get(id=topic_id)
    topic_user = topic_specific.user
    entries = topic_specific.entry_set.order_by('date_added')
    context = {'topic': topic_specific, 'topic_user': topic_user, 'entries': entries}
    return render(request, 'LAS_LOG/topic.html', context)


@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = TopicForm()
    else:
        # POST提交的数据,对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('LAS_LOGs:topics'))
    context = {'form': form}
    return render(request, 'LAS_LOG/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """在特定的主题中添加新条目"""

    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # 未提交数据,创建一个空表单
        form = EntryForm()
    else:
        # POST提交的数据,对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('LAS_LOGs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'LAS_LOG/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """编辑既有条目"""

    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        # 初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # POST提交的数据，对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('LAS_LOGs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'LAS_LOG/edit_entry.html', context)


@login_required
def links(request):
    all_link = Link.objects.order_by('date_added')
    context = {'links': all_link}
    return render(request, 'LAS_LOG/links.html', context)


@login_required()
def new_link(request):
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = LinkForm()
    else:
        # POST提交的数据,对数据进行处理
        form = LinkForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('LAS_LOGs:links'))
    context = {'form': form}
    return render(request, 'LAS_LOG/new_link.html', context)

resources/templates/LAS_LOG/base.html
{% load bootstrap3 %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>LAS Community Centre</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
          </button>
        <a class="navbar-brand" href="{% url 'LAS_LOGs:index' %}">
            LAS Community Centre</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'LAS_LOGs:topics' %}">Topics</a></li>
            <li><a href="{% url 'LAS_LOGs:links' %}">Links</a> </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
            {% else %}

              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </div>
  </body>
</html>

resources/templates/LAS_LOG/edit_entry.html
{% extends "LAS_LOG/base.html" %}
{% block content %}
 <p><a href="{% url 'LAS_LOGs:topic' topic.id %}">{{ topic }}</a></p>

 <p>Edit entry:</p>

 <form action="{% url 'LAS_LOGs:edit_entry' entry.id %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button name="submit"> Save changes</button>
 </form>
{% endblock content %}

resources/templates/LAS_LOG/index.html
<head>
  <style>
    body {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      background-size: cover;
      background-position: center;
    }

    .centered {
      text-align: center;
    }

    p {
      font-family: "Smiley Sans", Arial;
      font-size: 25px;
    }
  </style>
</head>

<body style="background-image: url('../../static/background1.png');">
  <div class="centered">
    <p>Welcome to LAS Community Centre!</p>
    <p>LAS Community Centre帮助LAS玩家记录自己在服务器中所做的事，以及给其他玩家的留言 -- typo</p>
    <p><a href="{% url 'topics' %}">Topics</a></p>
  </div>
</body>

resources/templates/LAS_LOG/links.html
{% extends "LAS_LOG/base.html" %}
{% block content %}
  <style>
    .custom-font-link {
      font-family: "Smiley Sans", Arial;
      font-size: 28px;
      color: black;
    }
    .custom-font-links {
      font-family: "Smiley Sans", Arial;
      font-size: 25px;
      color: blue;
      font-weight: bold;
      text-decoration: underline;
      cursor: pointer;
    }
  </style>

  <p class="custom-font-link"> Links</p>

  <ul>
    {% for link in links %}
      <li class="custom-font-link">
        <p>
          <a href= "link.text" id="link.id">{{ link }}</a>

          <script>
            var link = document.getElementById("link.id");
            link.addEventListener("click", function(event) {
              event.preventDefault();
              var url = document.getElementById("myLink")
              window.open(link.text)
            });
          </script>
        </p>
      </li>
    {% empty %}
      <li class="custom-font-link" >No links have been added yet.</li>
    {% endfor %}
  </ul>
  <li class="custom-font-link">
    <a href="{% url 'LAS_LOGs:new_link' %}">Add a new link:</a>
  </li>
{% endblock content %}

resources/templates/LAS_LOG/new_entry.html
{% extends "LAS_LOG/base.html" %}
{% block content %}
  <p><a href="{% url 'LAS_LOGs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Add a new entry:</p>
  <form action="{% url 'LAS_LOGs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Submit entry</button>
  </form>

{% endblock content %}

resources/templates/LAS_LOG/new_link.html
{% extends "LAS_LOG/base.html" %}
{% block content %}
  <p>Add a new link:</p>

  <form action="{% url 'LAS_LOGs:new_link' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit link</button>
  </form>

{% endblock content %}

resources/templates/LAS_LOG/new_topic.html
{% extends "LAS_LOG/base.html" %}
{% block content %} 
 <p>Add a new topic:</p> 
 
  <form action="{% url 'LAS_LOGs:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
  <button name="submit">Submit topic</button>
 </form> 
 
{% endblock content %}

resources/templates/LAS_LOG/topic.html
{% extends 'LAS_LOG/base.html' %}

{% block content %}
  <style>
    .custom-font-time {
      font-family: "Smiley Sans", Arial;
      font-size: 25px;
      color: #333;
    }
    .custom-font-topic {
      font-family: "Smiley Sans", Arial;
      font-size: 28px;
      color: #333;
    }
  </style>

  <p class="custom-font-topic">Topic: {{ topic }} -- {{ topic_user }}</p>

  <p class="custom-font-time">Entries:</p>

  <p class="custom-font-time">
    <a href="{% url 'LAS_LOGs:new_entry' topic.id %}">Add new entry</a>
  </p>

  <ul>
  {% for entry in entries %}
    <li class="custom-font-time">
      <div>
        <p>{{ entry.date_added|date:'M d, Y H:i' }} -- {{ entry.user }}</p>
        <p>{{ entry.text }}</p>
        <p>
          <a href="{% url 'LAS_LOGs:edit_entry' entry.id %}">edit entry</a>
        </p>
      </div>
    </li>
  {% empty %}
    <li class="custom-font-time">
      There are no entries for this topic yet.
    </li>
  {% endfor %}
  </ul>

{% endblock content %}

resources/templates/LAS_LOG/topics.html
{% extends "LAS_LOG/base.html" %}
{% block content %}
  <style>
    .custom-font-topic {
      font-family: "Smiley Sans", Arial;
      font-size: 28px;
      color: #333;
    }
    .custom-font-topics {
      font-family: "Smiley Sans", Arial;
      font-size: 25px;
      color: black;
    }
  </style>

  <p class="custom-font-topic"> Topics</p>

  <ul>
    {% for topic in topics %}
      <li class="custom-font-topics">
        <a href="{% url 'LAS_LOGs:topic' topic.id %}">{{ topic }}</a>
      </li>
    {% empty %}
      <li class="custom-font-topics" >&emsp;No topics have been added yet.</li>
    {% endfor %}
  </ul>

  <li class="custom-font-topics">
        <a href="{% url 'LAS_LOGs:new_topic' %}">Add a new topic:</a>
  </li>

{% endblock content %}